export type ButtonVariant = 'primary' | 'default' | 'secondary' | 'link' | 'danger'
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'
export type IconButtonSize = 'xs' | 'sm'
export type ButtonFontSize = 'xs' | 'sm' | 'md' | 'lg'
export type ButtonFontWeight = 'regular' | 'semibold'
export type ButtonLineHeight = 'default' | 'sm' | 'md' | 'lg'
